version: 2.1 
jobs:   
 build:     
  working_directory: ~/app     
  docker:       
    - image: circleci/node:18.7.0     
  steps:       
    - checkout              
    - restore_cache:
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
    - restore_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}
    - run: yarn install --frozen-lockfile
    - save_cache:
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
        paths:
          - ~/.cache/yarn
    - save_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}
        paths:
          - ./node_modules                          
run:           
  name: Run tests           
  command: yarn test