version: 2.1 
jobs:   
 build:     
  working_directory: ~/CICD_Demo    
  docker:       
    - image: cimg/node:18.7.0     
  steps:       
    - checkout              
    - restore_cache:
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
    - restore_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}
    - run: yarn install
    - save_cache:
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
        paths:
          - ~/.cache/yarn
    - save_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}
        paths:
          - ./node_modules                          
    - run:           
        name: Run tests           
        command: yarn run test